//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeCrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrangeCrypt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹异常：{0} 的本地化字符串。
        /// </summary>
        internal static string AbnormalFolderMessage {
            get {
                return ResourceManager.GetString("AbnormalFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前文件： 的本地化字符串。
        /// </summary>
        internal static string CurrentFileLabel {
            get {
                return ResourceManager.GetString("CurrentFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功清除系统关联 的本地化字符串。
        /// </summary>
        internal static string DeAssociationSuccessMessage {
            get {
                return ResourceManager.GetString("DeAssociationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解密文件夹失败，临时文件已清理 的本地化字符串。
        /// </summary>
        internal static string DecryptFailedWithDeletionMessage {
            get {
                return ResourceManager.GetString("DecryptFailedWithDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解密文件夹失败，临时文件清理失败，请手动清理 的本地化字符串。
        /// </summary>
        internal static string DecryptFailedWithoutDeletionMessage {
            get {
                return ResourceManager.GetString("DecryptFailedWithoutDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹解密成功 的本地化字符串。
        /// </summary>
        internal static string DecryptSuccessMessage {
            get {
                return ResourceManager.GetString("DecryptSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹解密成功，但加密容器未能删除，请手动清理 的本地化字符串。
        /// </summary>
        internal static string DecryptSuccessWithoutDeletionMessage {
            get {
                return ResourceManager.GetString("DecryptSuccessWithoutDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功注册系统关联 的本地化字符串。
        /// </summary>
        internal static string DoAssociationSuccessMessage {
            get {
                return ResourceManager.GetString("DoAssociationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已在运行中，本实例即将退出。 的本地化字符串。
        /// </summary>
        internal static string DuplicateInstanceMessage {
            get {
                return ResourceManager.GetString("DuplicateInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, 进度: {1:F1}% 的本地化字符串。
        /// </summary>
        internal static string EncryptStatusFormat {
            get {
                return ResourceManager.GetString("EncryptStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹加密失败，残余的加密文件已清理 的本地化字符串。
        /// </summary>
        internal static string FailedWithDeletionMessage {
            get {
                return ResourceManager.GetString("FailedWithDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹加密失败，残余的加密文件夹删除失败，请手动清理 的本地化字符串。
        /// </summary>
        internal static string FailedWithoutDeletionMessage {
            get {
                return ResourceManager.GetString("FailedWithoutDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹挂载点被占用 的本地化字符串。
        /// </summary>
        internal static string FolderAlreadyExistMessage {
            get {
                return ResourceManager.GetString("FolderAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夹密文件夹 的本地化字符串。
        /// </summary>
        internal static string FriendlyTypeName {
            get {
                return ResourceManager.GetString("FriendlyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常加密容器文件 的本地化字符串。
        /// </summary>
        internal static string InvalidEncryptedFileMessage {
            get {
                return ResourceManager.GetString("InvalidEncryptedFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string MenuConfig {
            get {
                return ResourceManager.GetString("MenuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除系统关联 的本地化字符串。
        /// </summary>
        internal static string MenuConfigDeAssociation {
            get {
                return ResourceManager.GetString("MenuConfigDeAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册系统关联 的本地化字符串。
        /// </summary>
        internal static string MenuConfigDoAssociation {
            get {
                return ResourceManager.GetString("MenuConfigDoAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string MenuEmpty {
            get {
                return ResourceManager.GetString("MenuEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已解密的文件夹 的本地化字符串。
        /// </summary>
        internal static string MenuMountedFolders {
            get {
                return ResourceManager.GetString("MenuMountedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载全部 的本地化字符串。
        /// </summary>
        internal static string MenuUnmountAll {
            get {
                return ResourceManager.GetString("MenuUnmountAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载并退出 的本地化字符串。
        /// </summary>
        internal static string MenuUnmountAndExit {
            get {
                return ResourceManager.GetString("MenuUnmountAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string MsgboxInfoTitle {
            get {
                return ResourceManager.GetString("MsgboxInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要管理员权限 的本地化字符串。
        /// </summary>
        internal static string NeedAdminMessage {
            get {
                return ResourceManager.GetString("NeedAdminMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本程序的主实例必须以管理员权限运行 的本地化字符串。
        /// </summary>
        internal static string NoAdministrativeMessage {
            get {
                return ResourceManager.GetString("NoAdministrativeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取用户会话 的本地化字符串。
        /// </summary>
        internal static string NoUserSessionMessage {
            get {
                return ResourceManager.GetString("NoUserSessionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密文件夹优化失败，临时文件已删除 的本地化字符串。
        /// </summary>
        internal static string OptimizeFailedWithDeletionMessage {
            get {
                return ResourceManager.GetString("OptimizeFailedWithDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密文件夹优化失败，临时文件清理失败，请手动清理 的本地化字符串。
        /// </summary>
        internal static string OptimizeFailedWithoutDeletionMessage {
            get {
                return ResourceManager.GetString("OptimizeFailedWithoutDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密文件夹优化成功 的本地化字符串。
        /// </summary>
        internal static string OptimizeSuccessMessage {
            get {
                return ResourceManager.GetString("OptimizeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ProgramIcon {
            get {
                object obj = ResourceManager.GetObject("ProgramIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 夹密大师 的本地化字符串。
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功加密了目录：{0} 的本地化字符串。
        /// </summary>
        internal static string SuccessEncryptMessage {
            get {
                return ResourceManager.GetString("SuccessEncryptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹加密成功，但源文件夹未能全部删除，请手动清理 的本地化字符串。
        /// </summary>
        internal static string SuccessWithoutDeletionMessage {
            get {
                return ResourceManager.GetString("SuccessWithoutDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入密码 的本地化字符串。
        /// </summary>
        internal static string TitleEnterPassword {
            get {
                return ResourceManager.GetString("TitleEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹加密 的本地化字符串。
        /// </summary>
        internal static string TitleFolderEncrypt {
            get {
                return ResourceManager.GetString("TitleFolderEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未预料的错误：{0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string WordCancel {
            get {
                return ResourceManager.GetString("WordCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        internal static string WordConfirmPassword {
            get {
                return ResourceManager.GetString("WordConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密 的本地化字符串。
        /// </summary>
        internal static string WordEncrypt {
            get {
                return ResourceManager.GetString("WordEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string WordOk {
            get {
                return ResourceManager.GetString("WordOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优化 的本地化字符串。
        /// </summary>
        internal static string WordOptimize {
            get {
                return ResourceManager.GetString("WordOptimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string WordPassword {
            get {
                return ResourceManager.GetString("WordPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久解密 的本地化字符串。
        /// </summary>
        internal static string WordPermanentDecrypt {
            get {
                return ResourceManager.GetString("WordPermanentDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示密码 的本地化字符串。
        /// </summary>
        internal static string WordShowPassword {
            get {
                return ResourceManager.GetString("WordShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        internal static string WordUnlock {
            get {
                return ResourceManager.GetString("WordUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误，或容器文件受损 的本地化字符串。
        /// </summary>
        internal static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
    }
}
